// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { after, describe, it } from "node:test";

import { computeRuntimeClosure } from "../src/closure.js";
import { loadRootLockfile } from "../src/lockfile.js";
import { loadWorkspaceGraph, resolveTargetWorkspace } from "../src/workspace-graph.js";

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, undefined, 2)}\n`, "utf8");
}

async function buildPolicyRepo(requiredName = "required"): Promise<string> {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-policies-"));
  await writeJson(path.join(root, "package.json"), {
    name: "root",
    private: true,
    workspaces: ["packages/*"],
  });
  await writeJson(path.join(root, "packages/app/package.json"), {
    name: "app",
    version: "1.0.0",
    dependencies: {
      [requiredName]: "^1.0.0",
      aliased: "npm:actual-package@^1.0.0",
    },
    devDependencies: { devpkg: "^2.0.0" },
    optionalDependencies: {
      "optional-present": "^3.0.0",
      "optional-missing": "^4.0.0",
    },
    peerDependencies: { peerpkg: "^5.0.0" },
  });
  await fs.writeFile(path.join(root, "packages/app/index.js"), "export const app = 1;\n");
  await writeJson(path.join(root, "package-lock.json"), {
    name: "root",
    lockfileVersion: 3,
    packages: {
      "": { name: "root" },
      "packages/app": { name: "app", version: "1.0.0" },
      "node_modules/app": { resolved: "packages/app", link: true },
      "node_modules/required": {
        version: "1.1.0",
        resolved: "https://r/required-1.1.0.tgz",
        integrity: "sha512-required",
      },
      "node_modules/aliased": {
        name: "actual-package",
        version: "1.2.0",
        resolved: "https://r/actual-package-1.2.0.tgz",
        integrity: "sha512-alias",
      },
      "node_modules/devpkg": {
        version: "2.1.0",
        resolved: "https://r/devpkg-2.1.0.tgz",
        integrity: "sha512-dev",
      },
      "node_modules/optional-present": {
        version: "3.1.0",
        resolved: "https://r/optional-present-3.1.0.tgz",
        integrity: "sha512-optional",
      },
      "node_modules/peerpkg": {
        version: "5.1.0",
        resolved: "https://r/peerpkg-5.1.0.tgz",
        integrity: "sha512-peer",
      },
    },
  });
  return root;
}

async function closureFor(
  root: string,
  options: { includeDevDependencies?: boolean; includeOptionalDependencies?: boolean },
) {
  const graph = await loadWorkspaceGraph(root);
  const lockfile = await loadRootLockfile(root);
  return computeRuntimeClosure(graph, lockfile, resolveTargetWorkspace(graph, "app"), options);
}

describe("runtime closure policies", () => {
  const cleanups: string[] = [];

  after(async () => {
    for (const root of cleanups) {
      await fs.rm(root, { recursive: true, force: true });
    }
  });

  it("includes enabled optional dependencies, resolves aliases, and warns for missing optionals", async () => {
    const root = await buildPolicyRepo();
    cleanups.push(root);

    const closure = await closureFor(root, {
      includeOptionalDependencies: true,
    });
    const registry = [...closure.registryPackages.values()]
      .map((entry) => `${entry.name}@${entry.version}`)
      .toSorted();

    assert.deepEqual(registry, ["aliased@1.2.0", "optional-present@3.1.0", "required@1.1.0"]);
    assert.equal(
      closure.registryPackages.get("aliased@1.2.0")?.lockfileKey,
      "node_modules/aliased",
    );
    assert.equal(registry.includes("peerpkg@5.1.0"), false);
    assert.deepEqual(closure.warnings, [
      'Optional registry dependency "optional-missing" (from "packages/app") was not found in the root lockfile; it will be omitted from the filtered lockfile.',
    ]);
  });

  it("excludes dev, optional, and peer dependencies by default", async () => {
    const root = await buildPolicyRepo();
    cleanups.push(root);

    const closure = await closureFor(root, {});
    const registry = [...closure.registryPackages.values()]
      .map((entry) => `${entry.name}@${entry.version}`)
      .toSorted();

    assert.deepEqual(registry, ["aliased@1.2.0", "required@1.1.0"]);
    assert.deepEqual(closure.warnings, []);
  });

  it("includes target dev dependencies when enabled", async () => {
    const root = await buildPolicyRepo();
    cleanups.push(root);

    const closure = await closureFor(root, { includeDevDependencies: true });
    const registry = [...closure.registryPackages.values()]
      .map((entry) => `${entry.name}@${entry.version}`)
      .toSorted();

    assert.deepEqual(registry, ["aliased@1.2.0", "devpkg@2.1.0", "required@1.1.0"]);
    assert.deepEqual(closure.warnings, []);
  });

  it("fails when a required runtime dependency is absent from the lockfile", async () => {
    const root = await buildPolicyRepo("missing-required");
    cleanups.push(root);

    await assert.rejects(
      closureFor(root, {}),
      /Runtime dependency "missing-required".*package-lock\.json is out of sync/s,
    );
  });
});
