// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { after, describe, it } from "node:test";

import { computeRuntimeClosure } from "../src/closure.js";
import { runWsDeploy } from "../src/deploy.js";
import { loadRepositoryLockfile } from "../src/lockfile.js";
import { loadWorkspaceGraph, resolveTargetWorkspace } from "../src/workspace-graph.js";

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, undefined, 2)}\n`, "utf8");
}

async function buildPolicyRepository(requiredName = "required"): Promise<string> {
  const repositoryDir = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-policies-"));
  await writeJson(path.join(repositoryDir, "package.json"), {
    name: "repository",
    private: true,
    workspaces: ["packages/*"],
  });
  await writeJson(path.join(repositoryDir, "packages/app/package.json"), {
    name: "app",
    version: "1.0.0",
    dependencies: {
      [requiredName]: "^1.0.0",
      aliased: "npm:actual-package@^1.0.0",
    },
    devDependencies: { devpkg: "^2.0.0" },
    optionalDependencies: {
      "optional-present": "^3.0.0",
      "optional-missing": "^4.0.0",
    },
    peerDependencies: { peerpkg: "^5.0.0" },
    peerDependenciesMeta: { peerpkg: { optional: true } },
  });
  await fs.writeFile(path.join(repositoryDir, "packages/app/index.js"), "export const app = 1;\n");
  await writeJson(path.join(repositoryDir, "package-lock.json"), {
    name: "repository",
    lockfileVersion: 3,
    packages: {
      "": { name: "repository" },
      "packages/app": { name: "app", version: "1.0.0" },
      "node_modules/app": { resolved: "packages/app", link: true },
      "node_modules/required": {
        version: "1.1.0",
        resolved: "https://r/required-1.1.0.tgz",
        integrity: "sha512-required",
      },
      "node_modules/aliased": {
        name: "actual-package",
        version: "1.2.0",
        resolved: "https://r/actual-package-1.2.0.tgz",
        integrity: "sha512-alias",
      },
      "node_modules/devpkg": {
        version: "2.1.0",
        resolved: "https://r/devpkg-2.1.0.tgz",
        integrity: "sha512-dev",
      },
      "node_modules/optional-present": {
        version: "3.1.0",
        resolved: "https://r/optional-present-3.1.0.tgz",
        integrity: "sha512-optional",
      },
      "node_modules/peerpkg": {
        version: "5.1.0",
        resolved: "https://r/peerpkg-5.1.0.tgz",
        integrity: "sha512-peer",
      },
    },
  });
  return repositoryDir;
}

async function closureFor(
  repositoryDir: string,
  options: { includeDevDependencies?: boolean; includeOptionalDependencies?: boolean },
) {
  const graph = await loadWorkspaceGraph(repositoryDir);
  const lockfile = await loadRepositoryLockfile(repositoryDir);
  return computeRuntimeClosure(graph, lockfile, resolveTargetWorkspace(graph, "app"), options);
}

describe("runtime closure policies", () => {
  const cleanups: string[] = [];

  after(async () => {
    for (const repositoryDir of cleanups) {
      await fs.rm(repositoryDir, { recursive: true, force: true });
    }
  });

  it("includes enabled optional dependencies, resolves aliases, and warns for missing optionals", async () => {
    const repositoryDir = await buildPolicyRepository();
    cleanups.push(repositoryDir);

    const closure = await closureFor(repositoryDir, {
      includeOptionalDependencies: true,
    });
    const registry = [...closure.registryPackages.values()]
      .map((entry) => `${entry.name}@${entry.version}`)
      .toSorted();

    assert.deepEqual(registry, ["aliased@1.2.0", "optional-present@3.1.0", "required@1.1.0"]);
    assert.equal(
      closure.registryPackages.get("aliased@1.2.0")?.lockfileKey,
      "node_modules/aliased",
    );
    assert.equal(registry.includes("peerpkg@5.1.0"), false);
    assert.deepEqual(closure.warnings, [
      'Optional registry dependency "optional-missing" (from "packages/app") was not found in the repository lockfile; it will be omitted from the filtered lockfile.',
    ]);
  });

  it("excludes dev, optional, and peer dependencies by default", async () => {
    const repositoryDir = await buildPolicyRepository();
    cleanups.push(repositoryDir);

    const closure = await closureFor(repositoryDir, {});
    const registry = [...closure.registryPackages.values()]
      .map((entry) => `${entry.name}@${entry.version}`)
      .toSorted();

    assert.deepEqual(registry, ["aliased@1.2.0", "required@1.1.0"]);
    assert.deepEqual(closure.warnings, []);
  });

  it("includes target dev dependencies when enabled", async () => {
    const repositoryDir = await buildPolicyRepository();
    cleanups.push(repositoryDir);

    const closure = await closureFor(repositoryDir, { includeDevDependencies: true });
    const registry = [...closure.registryPackages.values()]
      .map((entry) => `${entry.name}@${entry.version}`)
      .toSorted();

    assert.deepEqual(registry, ["aliased@1.2.0", "devpkg@2.1.0", "required@1.1.0"]);
    assert.deepEqual(closure.warnings, []);
  });

  it("fails when a required runtime dependency is absent from the lockfile", async () => {
    const repositoryDir = await buildPolicyRepository("missing-required");
    cleanups.push(repositoryDir);

    await assert.rejects(
      closureFor(repositoryDir, {}),
      /Runtime dependency "missing-required".*package-lock\.json is out of sync/s,
    );
  });

  it("lets optional declarations override regular and dev dependencies throughout the closure", async () => {
    const repositoryDir = await buildPolicyRepository();
    cleanups.push(repositoryDir);
    await writeJson(path.join(repositoryDir, "packages/app/package.json"), {
      name: "app",
      version: "1.0.0",
      dependencies: { required: "^1.0.0", "optional-missing": "^1.0.0" },
      devDependencies: { "optional-missing": "^2.0.0" },
      optionalDependencies: { "optional-missing": "^4.0.0" },
    });
    const lockfile = await loadRepositoryLockfile(repositoryDir);
    const required = lockfile.packages["node_modules/required"]!;
    required.dependencies = { "optional-missing": "^1.0.0" };
    required.optionalDependencies = { "optional-missing": "^4.0.0" };
    await writeJson(path.join(repositoryDir, "package-lock.json"), lockfile);

    const omitted = await closureFor(repositoryDir, { includeDevDependencies: true });
    assert.deepEqual([...omitted.registryPackages.keys()], ["required@1.1.0"]);
    assert.deepEqual(omitted.warnings, []);

    const deployment = await runWsDeploy({
      repositoryDir,
      targetWorkspace: "app",
      deploymentDir: path.join(repositoryDir, "deployment"),
      installMode: "none",
      includeDevDependencies: true,
    });
    assert.deepEqual(deployment.lockfile.packages[""]?.dependencies, { required: "^1.0.0" });
    assert.deepEqual(deployment.lockfile.packages[""]?.devDependencies, {});
    assert.equal(deployment.lockfile.packages[""]?.optionalDependencies, undefined);
    assert.deepEqual(deployment.lockfile.packages["node_modules/required"]?.dependencies, {});
    assert.equal(
      deployment.lockfile.packages["node_modules/required"]?.optionalDependencies,
      undefined,
    );

    const included = await closureFor(repositoryDir, {
      includeDevDependencies: true,
      includeOptionalDependencies: true,
    });
    assert.deepEqual([...included.registryPackages.keys()], ["required@1.1.0"]);
    assert.equal(included.warnings.length, 2);
    assert.ok(
      included.warnings.every((warning) =>
        warning.startsWith('Optional registry dependency "optional-missing"'),
      ),
    );
  });

  it("does not retain dev dependencies when a workspace graph is reused", async () => {
    const repositoryDir = await buildPolicyRepository();
    cleanups.push(repositoryDir);
    const graph = await loadWorkspaceGraph(repositoryDir);
    const lockfile = await loadRepositoryLockfile(repositoryDir);
    const target = resolveTargetWorkspace(graph, "app");
    const originalDependencies = [...target.dependencies];

    const development = await computeRuntimeClosure(graph, lockfile, target, {
      includeDevDependencies: true,
    });
    const production = await computeRuntimeClosure(graph, lockfile, target, {});

    assert.ok(development.registryPackages.has("devpkg@2.1.0"));
    assert.equal(production.registryPackages.has("devpkg@2.1.0"), false);
    assert.deepEqual(target.dependencies, originalDependencies);
  });

  it("includes required target peers from the lockfile without including target dev dependencies", async () => {
    const repositoryDir = await buildPolicyRepository();
    cleanups.push(repositoryDir);
    await writeJson(path.join(repositoryDir, "packages/app/package.json"), {
      name: "app",
      version: "1.0.0",
      peerDependencies: { peerpkg: "^5.0.0", missing: "*" },
      peerDependenciesMeta: { missing: { optional: true } },
      devDependencies: { devpkg: "^2.0.0" },
    });

    const closure = await closureFor(repositoryDir, {});

    assert.deepEqual([...closure.registryPackages.keys()], ["peerpkg@5.1.0"]);
    assert.deepEqual(closure.warnings, []);
  });

  it("rechecks an optional subtree when a required consumer also needs it", async () => {
    const repositoryDir = await buildPolicyRepository();
    cleanups.push(repositoryDir);
    await writeJson(path.join(repositoryDir, "packages/app/package.json"), {
      name: "app",
      version: "1.0.0",
      dependencies: { first: "*", required: "*" },
    });
    const lockfile = await loadRepositoryLockfile(repositoryDir);
    lockfile.packages["node_modules/first"] = {
      version: "1.0.0",
      optionalDependencies: { shared: "*" },
    };
    lockfile.packages["node_modules/required"]!.dependencies = { shared: "*" };
    lockfile.packages["node_modules/shared"] = {
      version: "1.0.0",
      dependencies: { absent: "*" },
    };
    await writeJson(path.join(repositoryDir, "package-lock.json"), lockfile);

    await assert.rejects(
      closureFor(repositoryDir, { includeOptionalDependencies: true }),
      /Runtime dependency "absent".*package-lock\.json is out of sync/s,
    );
  });

  it("omits missing optional workspace, directory, and tarball sources", async () => {
    const repositoryDir = await buildPolicyRepository();
    cleanups.push(repositoryDir);
    await writeJson(path.join(repositoryDir, "packages/app/package.json"), {
      name: "app",
      version: "1.0.0",
      optionalDependencies: {
        "missing-workspace": "workspace:*",
        "missing-directory": "file:../../absent",
        "missing-tarball": "file:../../absent.tgz",
      },
    });

    const result = await runWsDeploy({
      repositoryDir,
      targetWorkspace: "app",
      deploymentDir: path.join(repositoryDir, "deployment"),
      installMode: "none",
      includeOptionalDependencies: true,
    });

    assert.equal(result.closure.localDependencies.size, 0);
    assert.equal(result.closure.registryPackages.size, 0);
    assert.deepEqual(result.lockfile.packages[""]?.optionalDependencies, {});
    assert.equal(result.warnings.length, 3);
    for (const name of ["missing-workspace", "missing-directory", "missing-tarball"]) {
      assert.ok(result.warnings.some((warning) => warning.includes(`"${name}"`)));
    }
  });
});
