// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { after, before, describe, it } from "node:test";

import { runWsDeploy } from "../src/deploy.js";
import type { PackageJson } from "../src/types.js";
import { buildFixtureRepository, cleanupFixture } from "./fixture.js";

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await fs.readFile(file, "utf8")) as T;
}

function fileReference(fromDir: string, packageDir: string): string {
  let relative = path.relative(fromDir, packageDir).replace(/\\/g, "/");
  if (!relative.startsWith(".")) {
    relative = `./${relative}`;
  }
  return `file:${relative}`;
}

describe("runWsDeploy (installMode none)", () => {
  let repositoryDir: string;
  let deploymentDir: string;

  before(async () => {
    repositoryDir = await buildFixtureRepository();
    deploymentDir = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-output-"));
    await fs.rm(deploymentDir, { recursive: true, force: true });
  });

  after(async () => {
    await cleanupFixture(repositoryDir);
    await fs.rm(deploymentDir, { recursive: true, force: true });
  });

  it("references local source packages by default and projects packed lockfile entries", async () => {
    const result = await runWsDeploy({
      repositoryDir,
      targetWorkspace: "foo",
      deploymentDir,
      installMode: "none",
    });

    // Deployment manifest: local deps rewritten, registry untouched, dev/workspaces removed.
    const deploymentManifest = await readJson<PackageJson>(
      path.join(deploymentDir, "package.json"),
    );
    const libReference = fileReference(deploymentDir, path.join(repositoryDir, "packages/lib"));
    const sharedReference = fileReference(deploymentDir, path.join(repositoryDir, "shared"));
    assert.equal(deploymentManifest.dependencies?.["lib"], libReference);
    assert.equal(deploymentManifest.dependencies?.["shared"], sharedReference);
    assert.equal(deploymentManifest.dependencies?.["somelib"], "^1.0.0");
    assert.equal(deploymentManifest.devDependencies, undefined);
    assert.equal(deploymentManifest.workspaces, undefined);

    await assert.rejects(fs.stat(path.join(deploymentDir, "local-packages")));

    // Filtered lockfile preserves exact versions; lodash@3 hoists to deployment node_modules
    // (its monorepo nesting under somelib was only forced by bar's lodash@4,
    // which is not part of foo's closure).
    const lockfile = result.lockfile;
    assert.equal(lockfile.packages["node_modules/somelib"]?.version, "1.2.0");
    assert.equal(
      lockfile.packages["node_modules/somelib"]?.resolved,
      "https://registry.npmjs.org/somelib/-/somelib-1.2.0.tgz",
    );
    assert.equal(lockfile.packages["node_modules/somelib"]?.integrity, "sha512-somelib");
    assert.equal(lockfile.packages["node_modules/lodash"]?.version, "3.10.1");
    assert.equal(lockfile.packages["node_modules/lodash"]?.integrity, "sha512-lodash3");
    assert.equal(lockfile.packages["node_modules/somelib/node_modules/lodash"], undefined);
    assert.equal(lockfile.packages["node_modules/leftpad"]?.version, "1.3.0");
    assert.equal(lockfile.packages["node_modules/lib"]?.link, undefined);
    assert.equal(lockfile.packages["node_modules/lib"]?.version, "2.0.0");
    assert.equal(lockfile.packages["node_modules/lib"]?.resolved, libReference);
    assert.equal(lockfile.packages["node_modules/shared"]?.resolved, sharedReference);
    // The unrelated lodash@4 (bar's) is excluded.
    assert.notEqual(lockfile.packages["node_modules/lodash"]?.version, "4.17.21");
  });

  it("copies and rewrites local packages when requested", async () => {
    const result = await runWsDeploy({
      repositoryDir,
      targetWorkspace: "foo",
      deploymentDir,
      installMode: "none",
      copyLocalPackages: true,
    });

    const deploymentManifest = await readJson<PackageJson>(
      path.join(deploymentDir, "package.json"),
    );
    assert.equal(deploymentManifest.dependencies?.["lib"], "file:./local-packages/lib");
    await fs.access(path.join(deploymentDir, "local-packages/lib/package.json"));
    assert.deepEqual(result.lockfile.packages["node_modules/lib"], {
      resolved: "local-packages/lib",
      link: true,
    });
  });
});
