// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { after, describe, it } from "node:test";

import { runWsDeploy } from "../src/deploy.js";
import type { NpmLockfile } from "../src/types.js";

/** Write a JSON file, creating parent directories. */
async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, undefined, 2)}\n`, "utf8");
}

/** Materialize a temporary repository from manifests and a repository lockfile. */
async function buildRepository(
  manifests: Record<string, unknown>,
  lockfile: NpmLockfile,
): Promise<string> {
  const repositoryDir = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-hoist-"));
  for (const [dir, manifest] of Object.entries(manifests)) {
    await writeJson(path.join(repositoryDir, dir, "package.json"), manifest);
    await fs.writeFile(path.join(repositoryDir, dir, "index.js"), "export default 1;\n", "utf8");
  }
  await writeJson(path.join(repositoryDir, "package-lock.json"), lockfile);
  return repositoryDir;
}

async function deploy(repositoryDir: string, target: string): Promise<NpmLockfile> {
  const deploymentDir = path.join(repositoryDir, "deployment");
  const result = await runWsDeploy({
    repositoryDir,
    targetWorkspace: target,
    deploymentDir,
    installMode: "none",
    copyLocalPackages: true,
  });
  return result.lockfile;
}

describe("projectLockfile hoisting", () => {
  const cleanups: string[] = [];
  after(async () => {
    for (const dir of cleanups) {
      await fs.rm(dir, { recursive: true, force: true });
    }
  });

  it("nests a conflicting version under the consumer that needs it", async () => {
    // foo needs somelib@1 (nested under foo in the repository); lib needs
    // somelib@2 (top-level in the repository). In the deployment, somelib@1
    // becomes top-level and somelib@2 must nest under lib.
    const repositoryDir = await buildRepository(
      {
        ".": { name: "repository", private: true, workspaces: ["packages/*"] },
        "packages/foo": {
          name: "foo",
          version: "1.0.0",
          dependencies: { lib: "workspace:*", somelib: "^1.0.0" },
        },
        "packages/lib": { name: "lib", version: "1.0.0", dependencies: { somelib: "^2.0.0" } },
      },
      {
        name: "repository",
        lockfileVersion: 3,
        requires: true,
        packages: {
          "": { name: "repository" },
          "packages/foo": { name: "foo", version: "1.0.0" },
          "packages/lib": { name: "lib", version: "1.0.0" },
          "node_modules/foo": { resolved: "packages/foo", link: true },
          "node_modules/lib": { resolved: "packages/lib", link: true },
          "node_modules/somelib": {
            version: "2.0.0",
            resolved: "https://r/s-2.0.0.tgz",
            integrity: "sha512-v2",
          },
          "packages/foo/node_modules/somelib": {
            version: "1.0.0",
            resolved: "https://r/s-1.0.0.tgz",
            integrity: "sha512-v1",
          },
        },
      },
    );
    cleanups.push(repositoryDir);

    const lockfile = await deploy(repositoryDir, "foo");

    assert.equal(lockfile.packages["node_modules/somelib"]?.version, "1.0.0");
    assert.equal(lockfile.packages["local-packages/lib/node_modules/somelib"]?.version, "2.0.0");
    assert.equal(lockfile.packages["node_modules/lib"]?.link, true);
  });

  it("hoists the most-used version to the deployment and nests the minority", async () => {
    // p1/p2/p3 need lodash@4, q needs lodash@3. In the monorepo, lodash@3 is at
    // the top level and lodash@4 is nested under each p. In the deployment, the
    // most-used version (lodash@4, 3 consumers) is top-level; lodash@3
    // (1 consumer) nests under q, inverting the repository layout.
    const repositoryDir = await buildRepository(
      {
        ".": { name: "repository", private: true, workspaces: ["packages/*"] },
        "packages/foo": {
          name: "foo",
          version: "1.0.0",
          dependencies: {
            p1: "workspace:*",
            p2: "workspace:*",
            p3: "workspace:*",
            q: "workspace:*",
          },
        },
        "packages/p1": { name: "p1", version: "1.0.0", dependencies: { lodash: "^4.0.0" } },
        "packages/p2": { name: "p2", version: "1.0.0", dependencies: { lodash: "^4.0.0" } },
        "packages/p3": { name: "p3", version: "1.0.0", dependencies: { lodash: "^4.0.0" } },
        "packages/q": { name: "q", version: "1.0.0", dependencies: { lodash: "^3.0.0" } },
      },
      {
        name: "repository",
        lockfileVersion: 3,
        requires: true,
        packages: {
          "": { name: "repository" },
          "packages/foo": { name: "foo", version: "1.0.0" },
          "packages/p1": { name: "p1", version: "1.0.0" },
          "packages/p2": { name: "p2", version: "1.0.0" },
          "packages/p3": { name: "p3", version: "1.0.0" },
          "packages/q": { name: "q", version: "1.0.0" },
          "node_modules/foo": { resolved: "packages/foo", link: true },
          "node_modules/p1": { resolved: "packages/p1", link: true },
          "node_modules/p2": { resolved: "packages/p2", link: true },
          "node_modules/p3": { resolved: "packages/p3", link: true },
          "node_modules/q": { resolved: "packages/q", link: true },
          "node_modules/lodash": {
            version: "3.0.0",
            resolved: "https://r/l-3.0.0.tgz",
            integrity: "sha512-l3",
          },
          "packages/p1/node_modules/lodash": {
            version: "4.0.0",
            resolved: "https://r/l-4.0.0.tgz",
            integrity: "sha512-l4",
          },
          "packages/p2/node_modules/lodash": {
            version: "4.0.0",
            resolved: "https://r/l-4.0.0.tgz",
            integrity: "sha512-l4",
          },
          "packages/p3/node_modules/lodash": {
            version: "4.0.0",
            resolved: "https://r/l-4.0.0.tgz",
            integrity: "sha512-l4",
          },
        },
      },
    );
    cleanups.push(repositoryDir);

    const lockfile = await deploy(repositoryDir, "foo");

    // Majority version at the top level of the deployment.
    assert.equal(lockfile.packages["node_modules/lodash"]?.version, "4.0.0");
    // Minority nested under its lone consumer.
    assert.equal(lockfile.packages["local-packages/q/node_modules/lodash"]?.version, "3.0.0");
    // The three majority consumers share the deployment copy (no per-consumer nesting).
    assert.equal(lockfile.packages["local-packages/p1/node_modules/lodash"], undefined);
    assert.equal(lockfile.packages["local-packages/p2/node_modules/lodash"], undefined);
    assert.equal(lockfile.packages["local-packages/p3/node_modules/lodash"], undefined);
  });

  it("keeps the target's direct version top-level when another version is more used", async () => {
    const repositoryDir = await buildRepository(
      {
        ".": { name: "repository", private: true, workspaces: ["packages/*"] },
        "packages/foo": {
          name: "foo",
          version: "1.0.0",
          dependencies: {
            p1: "workspace:*",
            p2: "workspace:*",
            p3: "workspace:*",
            somelib: "^1.0.0",
          },
        },
        "packages/p1": { name: "p1", version: "1.0.0", dependencies: { somelib: "^2.0.0" } },
        "packages/p2": { name: "p2", version: "1.0.0", dependencies: { somelib: "^2.0.0" } },
        "packages/p3": { name: "p3", version: "1.0.0", dependencies: { somelib: "^2.0.0" } },
      },
      {
        name: "repository",
        lockfileVersion: 3,
        requires: true,
        packages: {
          "": { name: "repository" },
          "packages/foo": { name: "foo", version: "1.0.0" },
          "packages/p1": { name: "p1", version: "1.0.0" },
          "packages/p2": { name: "p2", version: "1.0.0" },
          "packages/p3": { name: "p3", version: "1.0.0" },
          "node_modules/foo": { resolved: "packages/foo", link: true },
          "node_modules/p1": { resolved: "packages/p1", link: true },
          "node_modules/p2": { resolved: "packages/p2", link: true },
          "node_modules/p3": { resolved: "packages/p3", link: true },
          "node_modules/somelib": {
            version: "1.0.0",
            resolved: "https://r/s-1.0.0.tgz",
            integrity: "sha512-v1",
          },
          "packages/p1/node_modules/somelib": {
            version: "2.0.0",
            resolved: "https://r/s-2.0.0.tgz",
            integrity: "sha512-v2",
          },
          "packages/p2/node_modules/somelib": {
            version: "2.0.0",
            resolved: "https://r/s-2.0.0.tgz",
            integrity: "sha512-v2",
          },
          "packages/p3/node_modules/somelib": {
            version: "2.0.0",
            resolved: "https://r/s-2.0.0.tgz",
            integrity: "sha512-v2",
          },
        },
      },
    );
    cleanups.push(repositoryDir);

    const lockfile = await deploy(repositoryDir, "foo");

    assert.equal(lockfile.packages["node_modules/somelib"]?.version, "1.0.0");
    assert.equal(lockfile.packages["local-packages/p1/node_modules/somelib"]?.version, "2.0.0");
    assert.equal(lockfile.packages["local-packages/p2/node_modules/somelib"]?.version, "2.0.0");
    assert.equal(lockfile.packages["local-packages/p3/node_modules/somelib"]?.version, "2.0.0");
  });

  it("breaks equal usage ties by ascending version", async () => {
    const repositoryDir = await buildRepository(
      {
        ".": { name: "repository", private: true, workspaces: ["packages/*"] },
        "packages/foo": {
          name: "foo",
          version: "1.0.0",
          dependencies: { p1: "workspace:*", p2: "workspace:*" },
        },
        "packages/p1": { name: "p1", version: "1.0.0", dependencies: { somelib: "^2.0.0" } },
        "packages/p2": { name: "p2", version: "1.0.0", dependencies: { somelib: "^1.0.0" } },
      },
      {
        lockfileVersion: 3,
        packages: {
          "": { name: "repository" },
          "packages/foo": { name: "foo", version: "1.0.0" },
          "packages/p1": { name: "p1", version: "1.0.0" },
          "packages/p2": { name: "p2", version: "1.0.0" },
          "node_modules/foo": { resolved: "packages/foo", link: true },
          "node_modules/p1": { resolved: "packages/p1", link: true },
          "node_modules/p2": { resolved: "packages/p2", link: true },
          "packages/p1/node_modules/somelib": {
            version: "2.0.0",
            resolved: "https://r/s-2.0.0.tgz",
            integrity: "sha512-v2",
          },
          "packages/p2/node_modules/somelib": {
            version: "1.0.0",
            resolved: "https://r/s-1.0.0.tgz",
            integrity: "sha512-v1",
          },
        },
      },
    );
    cleanups.push(repositoryDir);

    const lockfile = await deploy(repositoryDir, "foo");

    assert.equal(lockfile.packages["node_modules/somelib"]?.version, "1.0.0");
    assert.equal(lockfile.packages["local-packages/p1/node_modules/somelib"]?.version, "2.0.0");
  });

  it("places a deep transitive conflict under the direct local consumer", async () => {
    const repositoryDir = await buildRepository(
      {
        ".": { name: "repository", private: true, workspaces: ["packages/*"] },
        "packages/foo": {
          name: "foo",
          version: "1.0.0",
          dependencies: { a: "workspace:*", b: "workspace:*" },
        },
        "packages/a": { name: "a", version: "1.0.0", dependencies: { x: "^1.0.0" } },
        "packages/b": { name: "b", version: "1.0.0", dependencies: { y: "^3.0.0" } },
      },
      {
        lockfileVersion: 3,
        packages: {
          "": { name: "repository" },
          "packages/foo": { name: "foo", version: "1.0.0" },
          "packages/a": { name: "a", version: "1.0.0" },
          "packages/b": { name: "b", version: "1.0.0" },
          "node_modules/foo": { resolved: "packages/foo", link: true },
          "node_modules/a": { resolved: "packages/a", link: true },
          "node_modules/b": { resolved: "packages/b", link: true },
          "node_modules/x": {
            version: "1.0.0",
            resolved: "https://r/x-1.0.0.tgz",
            integrity: "sha512-x1",
            dependencies: { y: "^2.0.0" },
          },
          "node_modules/y": {
            version: "2.0.0",
            resolved: "https://r/y-2.0.0.tgz",
            integrity: "sha512-y2",
          },
          "packages/b/node_modules/y": {
            version: "3.0.0",
            resolved: "https://r/y-3.0.0.tgz",
            integrity: "sha512-y3",
          },
        },
      },
    );
    cleanups.push(repositoryDir);

    const lockfile = await deploy(repositoryDir, "foo");

    assert.equal(lockfile.packages["node_modules/x"]?.version, "1.0.0");
    assert.equal(lockfile.packages["node_modules/y"]?.version, "2.0.0");
    assert.equal(lockfile.packages["local-packages/b/node_modules/y"]?.version, "3.0.0");
    assert.equal(lockfile.packages["node_modules/x/node_modules/y"], undefined);
  });

  it("terminates when registry dependencies contain a cycle", async () => {
    const repositoryDir = await buildRepository(
      {
        ".": { name: "repository", private: true, workspaces: ["packages/*"] },
        "packages/foo": {
          name: "foo",
          version: "1.0.0",
          dependencies: { a: "^1.0.0" },
        },
      },
      {
        lockfileVersion: 3,
        packages: {
          "": { name: "repository" },
          "packages/foo": { name: "foo", version: "1.0.0" },
          "node_modules/foo": { resolved: "packages/foo", link: true },
          "node_modules/a": {
            version: "1.0.0",
            resolved: "https://r/a-1.0.0.tgz",
            integrity: "sha512-a1",
            dependencies: { b: "^1.0.0" },
          },
          "node_modules/b": {
            version: "1.0.0",
            resolved: "https://r/b-1.0.0.tgz",
            integrity: "sha512-b1",
            dependencies: { a: "^1.0.0" },
          },
        },
      },
    );
    cleanups.push(repositoryDir);

    const lockfile = await deploy(repositoryDir, "foo");

    assert.equal(lockfile.packages["node_modules/a"]?.version, "1.0.0");
    assert.equal(lockfile.packages["node_modules/b"]?.version, "1.0.0");
    assert.equal(Object.keys(lockfile.packages).filter((key) => key.endsWith("/a")).length, 1);
    assert.equal(Object.keys(lockfile.packages).filter((key) => key.endsWith("/b")).length, 1);
  });

  it("deduplicates the same exact package version across lockfile contexts deterministically", async () => {
    const repositoryDir = await buildRepository(
      {
        ".": { name: "repository", private: true, workspaces: ["packages/*"] },
        "packages/foo": {
          name: "foo",
          version: "1.0.0",
          dependencies: { p1: "workspace:*", p2: "workspace:*" },
        },
        "packages/p1": { name: "p1", version: "1.0.0", dependencies: { x: "^1.0.0" } },
        "packages/p2": { name: "p2", version: "1.0.0", dependencies: { x: "^1.0.0" } },
      },
      {
        lockfileVersion: 3,
        packages: {
          "": { name: "repository" },
          "packages/foo": { name: "foo", version: "1.0.0" },
          "packages/p1": { name: "p1", version: "1.0.0" },
          "packages/p2": { name: "p2", version: "1.0.0" },
          "node_modules/foo": { resolved: "packages/foo", link: true },
          "node_modules/p1": { resolved: "packages/p1", link: true },
          "node_modules/p2": { resolved: "packages/p2", link: true },
          "packages/p1/node_modules/x": {
            version: "1.0.0",
            resolved: "https://r/x-context-one.tgz",
            integrity: "sha512-context-one",
            dependencies: { y: "*" },
          },
          "packages/p1/node_modules/x/node_modules/y": {
            version: "1.0.0",
            resolved: "https://r/y-1.0.0.tgz",
            integrity: "sha512-y1",
          },
          "packages/p2/node_modules/x": {
            version: "1.0.0",
            resolved: "https://r/x-context-one.tgz",
            integrity: "sha512-context-one",
            dependencies: { y: "*" },
          },
          "packages/p2/node_modules/x/node_modules/y": {
            version: "1.0.0",
            resolved: "https://r/y-1.0.0.tgz",
            integrity: "sha512-y1",
          },
        },
      },
    );
    cleanups.push(repositoryDir);

    const lockfile = await deploy(repositoryDir, "foo");

    assert.equal(lockfile.packages["node_modules/x"]?.resolved, "https://r/x-context-one.tgz");
    assert.equal(lockfile.packages["node_modules/x"]?.integrity, "sha512-context-one");
    assert.equal(lockfile.packages["node_modules/y"]?.version, "1.0.0");
    assert.equal(lockfile.packages["local-packages/p2/node_modules/x"], undefined);
    assert.equal(lockfile.packages["node_modules/y"]?.resolved, "https://r/y-1.0.0.tgz");
  });

  for (const differentTarball of [false, true]) {
    it(`preserves distinct same-version dependency contexts (different tarball=${differentTarball})`, async () => {
      const secondSource = differentTarball
        ? "https://r/library-fork.tgz"
        : "https://r/library.tgz";
      const repositoryDir = await buildRepository(
        {
          ".": { name: "repository", private: true, workspaces: ["packages/*"] },
          "packages/app": {
            name: "app",
            version: "1.0.0",
            dependencies: { first: "workspace:*", second: "workspace:*" },
          },
          "packages/first": { name: "first", version: "1.0.0", dependencies: { library: "*" } },
          "packages/second": { name: "second", version: "1.0.0", dependencies: { library: "*" } },
        },
        {
          lockfileVersion: 3,
          packages: {
            "": { name: "repository" },
            "packages/first/node_modules/library": {
              version: "1.0.0",
              resolved: "https://r/library.tgz",
              integrity: "sha512-library",
              dependencies: { child: "*" },
            },
            "packages/second/node_modules/library": {
              version: "1.0.0",
              resolved: secondSource,
              integrity: differentTarball ? "sha512-fork" : "sha512-library",
              dependencies: { child: "*" },
            },
            "packages/first/node_modules/library/node_modules/child": {
              version: "1.0.0",
              resolved: "https://r/child-1.tgz",
            },
            "packages/second/node_modules/library/node_modules/child": {
              version: "2.0.0",
              resolved: "https://r/child-2.tgz",
            },
          },
        },
      );
      cleanups.push(repositoryDir);

      const lockfile = await deploy(repositoryDir, "app");

      assert.equal(lockfile.packages["node_modules/library"]?.resolved, "https://r/library.tgz");
      assert.equal(
        lockfile.packages["local-packages/second/node_modules/library"]?.resolved,
        secondSource,
      );
      assert.equal(
        lockfile.packages["local-packages/second/node_modules/library"]?.integrity,
        differentTarball ? "sha512-fork" : "sha512-library",
      );
      assert.equal(lockfile.packages["node_modules/child"]?.version, "1.0.0");
      assert.equal(
        lockfile.packages["local-packages/second/node_modules/library/node_modules/child"]?.version,
        "2.0.0",
      );
    });
  }

  it("nests registry packages that share a name with a retained local workspace", async () => {
    const repositoryDir = await buildRepository(
      {
        ".": { name: "repository", private: true, workspaces: ["packages/*"] },
        "packages/app": {
          name: "app",
          version: "1.0.0",
          dependencies: { lib: "workspace:*", consumer: "*" },
        },
        "packages/lib": { name: "lib", version: "1.0.0" },
      },
      {
        lockfileVersion: 3,
        packages: {
          "": { name: "repository" },
          "node_modules/lib": { resolved: "packages/lib", link: true },
          "node_modules/consumer": { version: "1.0.0", dependencies: { lib: "^2.0.0" } },
          "node_modules/consumer/node_modules/lib": {
            version: "2.1.0",
            resolved: "https://r/lib-2.1.tgz",
          },
        },
      },
    );
    cleanups.push(repositoryDir);

    const lockfile = await deploy(repositoryDir, "app");

    assert.deepEqual(lockfile.packages["node_modules/lib"], {
      resolved: "local-packages/lib",
      link: true,
    });
    assert.equal(lockfile.packages["node_modules/consumer/node_modules/lib"]?.version, "2.1.0");
    assert.equal(
      lockfile.packages["node_modules/consumer/node_modules/lib"]?.resolved,
      "https://r/lib-2.1.tgz",
    );
  });
});
