// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { DEFAULT_INSTALL_MODE } from "../src/types.js";

describe("install mode defaults", () => {
  it("uses npm-ci for deployment runs that omit installMode", () => {
    assert.equal(DEFAULT_INSTALL_MODE, "npm-ci");
  });
});
