// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { after, describe, it } from "node:test";

import { runWsDeploy } from "../src/deploy.js";
import { loadRootLockfile } from "../src/lockfile.js";

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, undefined, 2)}\n`, "utf8");
}

async function buildRepo(lockfile: unknown, manifest?: object): Promise<string> {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-lockfile-"));
  await writeJson(path.join(root, "package.json"), {
    name: "root",
    private: true,
    workspaces: ["packages/*"],
  });
  await writeJson(
    path.join(root, "packages/app/package.json"),
    manifest ?? { name: "app", version: "1.0.0" },
  );
  await fs.writeFile(path.join(root, "packages/app/cli.js"), "console.log('app');\n", "utf8");
  await writeJson(path.join(root, "package-lock.json"), lockfile);
  return root;
}

describe("lockfile integration", () => {
  const cleanups: string[] = [];

  after(async () => {
    for (const root of cleanups) {
      await fs.rm(root, { recursive: true, force: true });
    }
  });

  it("preserves a v2 lockfile version and projected root manifest fields", async () => {
    const manifest = {
      name: "app",
      version: "1.0.0",
      bin: { app: "cli.js" },
      dependencies: { dep: "^1.0.0" },
      devDependencies: { devpkg: "^4.0.0" },
      optionalDependencies: { optional: "^2.0.0" },
      peerDependencies: { peer: "^3.0.0" },
    };
    const root = await buildRepo(
      {
        name: "root",
        lockfileVersion: 2,
        requires: true,
        packages: {
          "": { name: "root" },
          "packages/app": { name: "app", version: "1.0.0" },
          "node_modules/app": { resolved: "packages/app", link: true },
          "node_modules/dep": {
            version: "1.2.0",
            resolved: "https://r/dep-1.2.0.tgz",
            integrity: "sha512-dep",
          },
          "node_modules/optional": {
            version: "2.1.0",
            resolved: "https://r/optional-2.1.0.tgz",
            integrity: "sha512-optional",
            optional: true,
          },
          "node_modules/devpkg": {
            version: "4.1.0",
            resolved: "https://r/devpkg-4.1.0.tgz",
            integrity: "sha512-devpkg",
            dev: true,
          },
        },
      },
      manifest,
    );
    cleanups.push(root);

    const deployDir = path.join(root, "output");
    const result = await runWsDeploy({
      repoRoot: root,
      targetWorkspace: "app",
      deployDir,
      installMode: "none",
      includeDevDependencies: true,
      includeOptionalDependencies: true,
    });

    assert.equal(result.lockfile.lockfileVersion, 2);
    assert.deepEqual(result.lockfile.packages[""], manifest);
    assert.equal(result.lockfile.packages["node_modules/dep"]?.resolved, "https://r/dep-1.2.0.tgz");
    assert.equal(result.lockfile.packages["node_modules/dep"]?.integrity, "sha512-dep");
    assert.equal(result.lockfile.packages["node_modules/optional"]?.optional, true);
    assert.equal(result.lockfile.packages["node_modules/devpkg"]?.dev, true);
  });

  it("rejects a legacy lockfile without a packages map", async () => {
    const root = await buildRepo({
      name: "root",
      lockfileVersion: 1,
      dependencies: { dep: { version: "1.2.0" } },
    });
    cleanups.push(root);

    await assert.rejects(
      loadRootLockfile(root),
      /has no "packages" map \(lockfileVersion >= 2 is required\)/,
    );
  });
});
