// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { after, describe, it } from "node:test";

import { runWsDeploy } from "../src/deploy.js";
import { loadRepositoryLockfile } from "../src/lockfile.js";
import type { PackageJson } from "../src/types.js";

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, undefined, 2)}\n`, "utf8");
}

async function buildRepository(
  lockfile: unknown,
  manifest?: object,
  repositoryFields: object = {},
): Promise<string> {
  const repositoryDir = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-lockfile-"));
  await writeJson(path.join(repositoryDir, "package.json"), {
    name: "repository",
    private: true,
    workspaces: ["packages/*"],
    ...repositoryFields,
  });
  await writeJson(
    path.join(repositoryDir, "packages/app/package.json"),
    manifest ?? { name: "app", version: "1.0.0" },
  );
  await fs.writeFile(
    path.join(repositoryDir, "packages/app/cli.js"),
    "console.log('app');\n",
    "utf8",
  );
  await writeJson(path.join(repositoryDir, "package-lock.json"), lockfile);
  return repositoryDir;
}

describe("lockfile integration", () => {
  const cleanups: string[] = [];

  after(async () => {
    for (const repositoryDir of cleanups) {
      await fs.rm(repositoryDir, { recursive: true, force: true });
    }
  });

  it("preserves a v2 lockfile version and projected deployment manifest fields", async () => {
    const manifest = {
      name: "app",
      version: "1.0.0",
      bin: { app: "cli.js" },
      dependencies: { dep: "^1.0.0" },
      devDependencies: { devpkg: "^4.0.0" },
      optionalDependencies: { optional: "^2.0.0" },
      peerDependencies: { peer: "^3.0.0" },
      peerDependenciesMeta: { peer: { optional: true } },
    };
    const repositoryOverrides = { dep: "1.2.0" };
    const repositoryDir = await buildRepository(
      {
        name: "repository",
        lockfileVersion: 2,
        requires: true,
        packages: {
          "": { name: "repository" },
          "packages/app": { name: "app", version: "1.0.0" },
          "node_modules/app": { resolved: "packages/app", link: true },
          "node_modules/dep": {
            version: "1.2.0",
            resolved: "https://r/dep-1.2.0.tgz",
            integrity: "sha512-dep",
          },
          "node_modules/optional": {
            version: "2.1.0",
            resolved: "https://r/optional-2.1.0.tgz",
            integrity: "sha512-optional",
            optional: true,
          },
          "node_modules/devpkg": {
            version: "4.1.0",
            resolved: "https://r/devpkg-4.1.0.tgz",
            integrity: "sha512-devpkg",
            dev: true,
          },
        },
      },
      manifest,
      { overrides: repositoryOverrides },
    );
    cleanups.push(repositoryDir);

    const deploymentDir = path.join(repositoryDir, "output");
    const result = await runWsDeploy({
      repositoryDir,
      targetWorkspace: "app",
      deploymentDir,
      installMode: "none",
      includeDevDependencies: true,
      includeOptionalDependencies: true,
    });

    assert.equal(result.lockfile.lockfileVersion, 2);
    assert.deepEqual(result.lockfile.packages[""], manifest);
    assert.equal(result.lockfile.packages["node_modules/dep"]?.resolved, "https://r/dep-1.2.0.tgz");
    assert.equal(result.lockfile.packages["node_modules/dep"]?.integrity, "sha512-dep");
    assert.equal(result.lockfile.packages["node_modules/optional"]?.optional, true);
    assert.equal(result.lockfile.packages["node_modules/devpkg"]?.dev, true);
    const deploymentManifest = await fs
      .readFile(path.join(deploymentDir, "package.json"), "utf8")
      .then((value) => JSON.parse(value) as PackageJson);
    assert.deepEqual(deploymentManifest["overrides"], repositoryOverrides);
  });

  it("rejects a legacy lockfile without a packages map", async () => {
    const repositoryDir = await buildRepository({
      name: "repository",
      lockfileVersion: 1,
      dependencies: { dep: { version: "1.2.0" } },
    });
    cleanups.push(repositoryDir);

    await assert.rejects(
      loadRepositoryLockfile(repositoryDir),
      /has no "packages" map \(lockfileVersion >= 2 is required\)/,
    );
  });

  it("prefers npm-shrinkwrap.json and supports it without a package-lock.json", async () => {
    const repositoryDir = await buildRepository({
      lockfileVersion: 3,
      packages: { "": { name: "package-lock" } },
    });
    cleanups.push(repositoryDir);
    const shrinkwrap = {
      lockfileVersion: 3,
      packages: { "": { name: "shrinkwrap" } },
    };
    await writeJson(path.join(repositoryDir, "npm-shrinkwrap.json"), shrinkwrap);

    assert.deepEqual(await loadRepositoryLockfile(repositoryDir), shrinkwrap);
    await fs.rm(path.join(repositoryDir, "package-lock.json"));
    assert.deepEqual(await loadRepositoryLockfile(repositoryDir), shrinkwrap);
  });

  it("validates shrinkwraps instead of falling back to a different lockfile", async () => {
    const repositoryDir = await buildRepository({ lockfileVersion: 3, packages: {} });
    cleanups.push(repositoryDir);
    await writeJson(path.join(repositoryDir, "npm-shrinkwrap.json"), {
      lockfileVersion: 1,
      dependencies: { dep: { version: "1.0.0" } },
    });

    await assert.rejects(
      loadRepositoryLockfile(repositoryDir),
      /npm-shrinkwrap\.json.*has no "packages" map/,
    );
  });

  it("rejects unsupported versions and malformed package maps", async () => {
    const repositoryDir = await buildRepository({ lockfileVersion: 1, packages: {} });
    cleanups.push(repositoryDir);
    await assert.rejects(loadRepositoryLockfile(repositoryDir), /requires lockfileVersion >= 2/);

    await writeJson(path.join(repositoryDir, "package-lock.json"), {
      lockfileVersion: 3,
      packages: [],
    });
    await assert.rejects(loadRepositoryLockfile(repositoryDir), /has no "packages" map/);
  });

  it("reports a missing repository lockfile", async () => {
    const repositoryDir = await buildRepository({ lockfileVersion: 3, packages: {} });
    cleanups.push(repositoryDir);
    await fs.rm(path.join(repositoryDir, "package-lock.json"));

    await assert.rejects(loadRepositoryLockfile(repositoryDir), /Repository lockfile not found/);
  });
});
