// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { after, before, describe, it } from "node:test";

import { runWsDeploy } from "../src/deploy.js";
import type { PackageJson } from "../src/types.js";

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, undefined, 2)}\n`, "utf8");
}

async function writePackage(root: string, relativeDir: string, manifest: object): Promise<void> {
  const packageDir = path.join(root, relativeDir);
  await writeJson(path.join(packageDir, "package.json"), manifest);
  await fs.writeFile(path.join(packageDir, "index.js"), "export const value = 1;\n", "utf8");
}

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await fs.readFile(file, "utf8")) as T;
}

describe("monorepo structure integration", () => {
  let repo: string;
  let deployDir: string;

  before(async () => {
    repo = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-structures-"));
    deployDir = path.join(repo, "output");

    await writeJson(path.join(repo, "package.json"), {
      name: "root",
      private: true,
      workspaces: {
        packages: ["services/*", "groups/*/packages/*", "libs/*"],
      },
    });
    await writePackage(repo, "services/api", {
      name: "@acme/api",
      version: "1.0.0",
      dependencies: {
        "@acme/lib": "workspace:*",
        "file-a": "file:../../files/file-a",
      },
    });
    await writePackage(repo, "groups/platform/packages/lib", {
      name: "@acme/lib",
      version: "2.0.0",
      dependencies: { "@acme/shared": "workspace:^" },
    });
    await writePackage(repo, "libs/shared", {
      name: "@acme/shared",
      version: "3.0.0",
    });
    await writePackage(repo, "files/file-a", {
      name: "file-a",
      version: "4.0.0",
      dependencies: { "file-b": "file:../file-b" },
    });
    await writePackage(repo, "files/file-b", {
      name: "file-b",
      version: "5.0.0",
    });
    await writeJson(path.join(repo, "package-lock.json"), {
      name: "root",
      lockfileVersion: 3,
      packages: {
        "": { name: "root" },
        "services/api": { name: "@acme/api", version: "1.0.0" },
        "groups/platform/packages/lib": { name: "@acme/lib", version: "2.0.0" },
        "libs/shared": { name: "@acme/shared", version: "3.0.0" },
        "node_modules/@acme/api": { resolved: "services/api", link: true },
        "node_modules/@acme/lib": { resolved: "groups/platform/packages/lib", link: true },
        "node_modules/@acme/shared": { resolved: "libs/shared", link: true },
      },
    });
  });

  after(async () => {
    await fs.rm(repo, { recursive: true, force: true });
  });

  it("materializes nested scoped workspaces and recursive file dependencies", async () => {
    const result = await runWsDeploy({
      repoRoot: repo,
      targetWorkspace: "@acme/api",
      deployDir,
      installMode: "none",
    });

    assert.deepEqual([...result.closure.localDependencies.keys()].toSorted(), [
      "@acme/lib",
      "@acme/shared",
      "file-a",
      "file-b",
    ]);
    assert.equal(result.closure.localDependencies.get("@acme/lib")?.sourceType, "workspace");
    assert.equal(result.closure.localDependencies.get("@acme/shared")?.sourceType, "workspace");
    assert.equal(result.closure.localDependencies.get("file-a")?.sourceType, "file");
    assert.equal(result.closure.localDependencies.get("file-b")?.sourceType, "file");

    const rootManifest = await readJson<PackageJson>(path.join(deployDir, "package.json"));
    assert.equal(rootManifest.name, "@acme/api");
    assert.equal(rootManifest.dependencies?.["@acme/lib"], "file:./local-packages/@acme/lib");
    assert.equal(rootManifest.dependencies?.["file-a"], "file:./local-packages/file-a");

    const libManifest = await readJson<PackageJson>(
      path.join(deployDir, "local-packages/@acme/lib/package.json"),
    );
    assert.equal(libManifest.dependencies?.["@acme/shared"], "file:../shared");

    const fileManifest = await readJson<PackageJson>(
      path.join(deployDir, "local-packages/file-a/package.json"),
    );
    assert.equal(fileManifest.dependencies?.["file-b"], "file:../file-b");

    await fs.access(path.join(deployDir, "local-packages/@acme/shared/index.js"));
    await fs.access(path.join(deployDir, "local-packages/file-b/index.js"));
    assert.deepEqual(result.lockfile.packages["node_modules/@acme/lib"], {
      resolved: "local-packages/@acme/lib",
      link: true,
    });
    assert.equal(result.lockfile.packages["local-packages/@acme/lib"]?.version, "2.0.0");
    assert.equal(result.lockfile.packages["local-packages/file-b"]?.version, "5.0.0");
  });
});
