// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { after, before, describe, it } from "node:test";

import { runWsDeploy } from "../src/deploy.js";
import type { PackageJson } from "../src/types.js";

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, undefined, 2)}\n`, "utf8");
}

async function writePackage(
  repositoryDir: string,
  relativeDir: string,
  manifest: object,
): Promise<void> {
  const packageDir = path.join(repositoryDir, relativeDir);
  await writeJson(path.join(packageDir, "package.json"), manifest);
  await fs.writeFile(path.join(packageDir, "index.js"), "export const value = 1;\n", "utf8");
}

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await fs.readFile(file, "utf8")) as T;
}

describe("monorepo structure integration", () => {
  let repositoryDir: string;
  let deploymentDir: string;

  before(async () => {
    repositoryDir = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-structures-"));
    deploymentDir = path.join(repositoryDir, "output");

    await writeJson(path.join(repositoryDir, "package.json"), {
      name: "fixture-repository",
      private: true,
      workspaces: {
        packages: ["services/*", "groups/*/packages/*", "libs/*"],
      },
    });
    await writePackage(repositoryDir, "services/api", {
      name: "@acme/api",
      version: "1.0.0",
      dependencies: {
        "@acme/lib": "workspace:*",
        "file-a": "file:../../files/file-a",
      },
      devDependencies: {
        "@acme/dev-tool": "workspace:*",
        "file-dev": "file:../../files/file-dev",
      },
    });
    await writePackage(repositoryDir, "groups/platform/packages/lib", {
      name: "@acme/lib",
      version: "2.0.0",
      dependencies: { "@acme/shared": "workspace:^" },
    });
    await writePackage(repositoryDir, "libs/shared", {
      name: "@acme/shared",
      version: "3.0.0",
    });
    await writePackage(repositoryDir, "libs/dev-tool", {
      name: "@acme/dev-tool",
      version: "6.0.0",
    });
    await writePackage(repositoryDir, "files/file-a", {
      name: "file-a",
      version: "4.0.0",
      dependencies: { "file-b": "file:../file-b" },
    });
    await writePackage(repositoryDir, "files/file-b", {
      name: "file-b",
      version: "5.0.0",
    });
    await writePackage(repositoryDir, "files/file-dev", {
      name: "file-dev",
      version: "7.0.0",
    });
    await writeJson(path.join(repositoryDir, "package-lock.json"), {
      name: "fixture-repository",
      lockfileVersion: 3,
      packages: {
        "": { name: "fixture-repository" },
        "services/api": { name: "@acme/api", version: "1.0.0" },
        "groups/platform/packages/lib": { name: "@acme/lib", version: "2.0.0" },
        "libs/shared": { name: "@acme/shared", version: "3.0.0" },
        "libs/dev-tool": { name: "@acme/dev-tool", version: "6.0.0" },
        "node_modules/@acme/api": { resolved: "services/api", link: true },
        "node_modules/@acme/lib": { resolved: "groups/platform/packages/lib", link: true },
        "node_modules/@acme/shared": { resolved: "libs/shared", link: true },
        "node_modules/@acme/dev-tool": { resolved: "libs/dev-tool", link: true },
      },
    });
  });

  after(async () => {
    await fs.rm(repositoryDir, { recursive: true, force: true });
  });

  it("materializes nested scoped workspaces and recursive file dependencies", async () => {
    const result = await runWsDeploy({
      repositoryDir,
      targetWorkspace: "@acme/api",
      deploymentDir,
      installMode: "none",
      copyLocalPackages: true,
    });

    assert.deepEqual([...result.closure.localDependencies.keys()].toSorted(), [
      "@acme/lib",
      "@acme/shared",
      "file-a",
      "file-b",
    ]);
    assert.equal(result.closure.localDependencies.get("@acme/lib")?.sourceType, "workspace");
    assert.equal(result.closure.localDependencies.get("@acme/shared")?.sourceType, "workspace");
    assert.equal(result.closure.localDependencies.get("file-a")?.sourceType, "file");
    assert.equal(result.closure.localDependencies.get("file-b")?.sourceType, "file");

    const deploymentManifest = await readJson<PackageJson>(
      path.join(deploymentDir, "package.json"),
    );
    assert.equal(deploymentManifest.name, "@acme/api");
    assert.equal(deploymentManifest.dependencies?.["@acme/lib"], "file:./local-packages/@acme/lib");
    assert.equal(deploymentManifest.dependencies?.["file-a"], "file:./local-packages/file-a");
    assert.equal(deploymentManifest.devDependencies, undefined);

    const libManifest = await readJson<PackageJson>(
      path.join(deploymentDir, "local-packages/@acme/lib/package.json"),
    );
    assert.equal(libManifest.dependencies?.["@acme/shared"], "file:../shared");

    const fileManifest = await readJson<PackageJson>(
      path.join(deploymentDir, "local-packages/file-a/package.json"),
    );
    assert.equal(fileManifest.dependencies?.["file-b"], "file:../file-b");

    await fs.access(path.join(deploymentDir, "local-packages/@acme/shared/index.js"));
    await fs.access(path.join(deploymentDir, "local-packages/file-b/index.js"));
    assert.deepEqual(result.lockfile.packages["node_modules/@acme/lib"], {
      resolved: "local-packages/@acme/lib",
      link: true,
    });
    assert.equal(result.lockfile.packages["local-packages/@acme/lib"]?.version, "2.0.0");
    assert.equal(result.lockfile.packages["local-packages/file-b"]?.version, "5.0.0");
  });

  it("materializes and rewrites enabled local dev dependencies", async () => {
    const result = await runWsDeploy({
      repositoryDir,
      targetWorkspace: "@acme/api",
      deploymentDir,
      installMode: "none",
      includeDevDependencies: true,
      copyLocalPackages: true,
    });

    assert.deepEqual([...result.closure.localDependencies.keys()].toSorted(), [
      "@acme/dev-tool",
      "@acme/lib",
      "@acme/shared",
      "file-a",
      "file-b",
      "file-dev",
    ]);

    const deploymentManifest = await readJson<PackageJson>(
      path.join(deploymentDir, "package.json"),
    );
    assert.equal(
      deploymentManifest.devDependencies?.["@acme/dev-tool"],
      "file:./local-packages/@acme/dev-tool",
    );
    assert.equal(
      deploymentManifest.devDependencies?.["file-dev"],
      "file:./local-packages/file-dev",
    );
    assert.deepEqual(
      result.lockfile.packages[""]?.devDependencies,
      deploymentManifest.devDependencies,
    );
    assert.deepEqual(result.lockfile.packages["node_modules/@acme/dev-tool"], {
      resolved: "local-packages/@acme/dev-tool",
      link: true,
    });
    assert.deepEqual(result.lockfile.packages["node_modules/file-dev"], {
      resolved: "local-packages/file-dev",
      link: true,
    });
    await fs.access(path.join(deploymentDir, "local-packages/@acme/dev-tool/index.js"));
    await fs.access(path.join(deploymentDir, "local-packages/file-dev/index.js"));
  });
});
