// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import { createServer, type Server } from "node:http";
import * as os from "node:os";
import * as path from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

import { execa } from "execa";

import type { NpmLockfile, PackageJson } from "../src/types.js";

const PROJECT_DIR = fileURLToPath(new URL("..", import.meta.url));
const CLI_PATH = path.join(PROJECT_DIR, "src/cli.ts");

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, undefined, 2)}\n`, "utf8");
}

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await fs.readFile(file, "utf8")) as T;
}

async function startTarballServer(files: Map<string, string>): Promise<{
  server: Server;
  origin: string;
}> {
  const server = createServer(async (request, response) => {
    const pathname = decodeURIComponent(new URL(request.url ?? "/", "http://localhost").pathname);
    const file = files.get(pathname);
    if (!file) {
      response.writeHead(404).end();
      return;
    }
    try {
      response.writeHead(200, { "content-type": "application/octet-stream" });
      response.end(await fs.readFile(file));
    } catch {
      response.writeHead(500).end();
    }
  });
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", resolve);
  });
  const address = server.address();
  assert.ok(address && typeof address === "object");
  return { server, origin: `http://127.0.0.1:${address.port}` };
}

async function closeServer(server: Server): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    server.close((error) => {
      if (error) {
        reject(error);
        return;
      }
      resolve();
    });
  });
}

async function packPackage(
  repositoryDir: string,
  tarballs: Map<string, string>,
  manifest: PackageJson,
): Promise<string> {
  const safeName = manifest.name?.replace(/[^a-zA-Z0-9.-]/g, "-") ?? "package";
  const sourceDir = path.join(repositoryDir, "package-sources", `${safeName}-${manifest.version}`);
  const outputDir = path.join(repositoryDir, "tarballs");
  await writeJson(path.join(sourceDir, "package.json"), manifest);
  await fs.writeFile(
    path.join(sourceDir, "index.js"),
    `export const version = ${JSON.stringify(manifest.version)};\n`,
    "utf8",
  );
  await fs.mkdir(outputDir, { recursive: true });
  const result = await execa("npm", ["pack", "--json", "--pack-destination", outputDir], {
    cwd: sourceDir,
  });
  const [{ filename }] = JSON.parse(result.stdout) as [{ filename: string }];
  tarballs.set(`/${filename}`, path.join(outputDir, filename));
  return filename;
}

async function assertMissing(file: string): Promise<void> {
  await assert.rejects(fs.access(file));
}

describe("ws-deploy CLI E2E", () => {
  it("runs npm ci with exact nested versions and excludes unrelated packages", async () => {
    const repositoryDir = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-npm-ci-"));
    const tarballs = new Map<string, string>();
    const { server, origin } = await startTarballServer(tarballs);

    try {
      const sharedV1 = await packPackage(repositoryDir, tarballs, {
        name: "fixture-shared",
        version: "1.0.0",
      });
      const sharedV2 = await packPackage(repositoryDir, tarballs, {
        name: "fixture-shared",
        version: "2.0.0",
      });
      const consumerA = await packPackage(repositoryDir, tarballs, {
        name: "fixture-consumer-a",
        version: "1.0.0",
        dependencies: { "fixture-shared": `${origin}/${sharedV1}` },
      });
      const consumerB = await packPackage(repositoryDir, tarballs, {
        name: "fixture-consumer-b",
        version: "1.0.0",
        dependencies: { "fixture-shared": `${origin}/${sharedV2}` },
      });
      const unrelated = await packPackage(repositoryDir, tarballs, {
        name: "fixture-unrelated-registry",
        version: "9.0.0",
      });
      const devRegistry = await packPackage(repositoryDir, tarballs, {
        name: "fixture-dev-registry",
        version: "4.0.0",
      });

      await writeJson(path.join(repositoryDir, "package.json"), {
        name: "fixture-repository",
        private: true,
        workspaces: ["packages/*"],
      });
      await writeJson(path.join(repositoryDir, "packages/app/package.json"), {
        name: "fixture-app",
        version: "1.0.0",
        dependencies: {
          "fixture-consumer-a": `${origin}/${consumerA}`,
          "fixture-consumer-b": `${origin}/${consumerB}`,
          "fixture-local-lib": "^1.0.0",
        },
        devDependencies: {
          "fixture-dev-local": "^2.0.0",
          "fixture-dev-registry": `${origin}/${devRegistry}`,
        },
      });
      await fs.writeFile(
        path.join(repositoryDir, "packages/app/index.js"),
        "export const app = 1;\n",
        "utf8",
      );
      await writeJson(path.join(repositoryDir, "packages/local-lib/package.json"), {
        name: "fixture-local-lib",
        version: "1.0.0",
      });
      await fs.writeFile(
        path.join(repositoryDir, "packages/local-lib/index.js"),
        "export const local = 1;\n",
        "utf8",
      );
      await writeJson(path.join(repositoryDir, "packages/dev-local/package.json"), {
        name: "fixture-dev-local",
        version: "2.0.0",
      });
      await fs.writeFile(
        path.join(repositoryDir, "packages/dev-local/index.js"),
        "export const dev = 1;\n",
        "utf8",
      );
      await writeJson(path.join(repositoryDir, "packages/unrelated/package.json"), {
        name: "fixture-unrelated-workspace",
        version: "1.0.0",
        dependencies: { "fixture-unrelated-registry": `${origin}/${unrelated}` },
      });

      await execa(
        "npm",
        ["install", "--package-lock-only", "--ignore-scripts", "--no-audit", "--no-fund"],
        { cwd: repositoryDir },
      );
      const sourceLockfile = await readJson<NpmLockfile>(
        path.join(repositoryDir, "package-lock.json"),
      );
      const deploymentDir = path.join(repositoryDir, "deployment");

      const cli = await execa(
        "node",
        [
          "--import",
          "tsx",
          CLI_PATH,
          "--target",
          "fixture-app",
          "--repository-dir",
          repositoryDir,
          "--deployment-dir",
          deploymentDir,
          "--install",
          "npm-ci",
          "--include-dev",
        ],
        {
          cwd: PROJECT_DIR,
        },
      );
      const projectedLockfile = await readJson<NpmLockfile>(
        path.join(deploymentDir, "package-lock.json"),
      );

      assert.match(cli.stdout, /Deployment ready:/);
      assert.match(cli.stdout, /local deps: 2, registry packages: 5/);
      assert.equal(cli.stderr, "");
      assert.equal(
        projectedLockfile.packages["node_modules/fixture-consumer-a"]?.integrity,
        sourceLockfile.packages["node_modules/fixture-consumer-a"]?.integrity,
      );
      assert.equal(
        projectedLockfile.packages["node_modules/fixture-consumer-b"]?.integrity,
        sourceLockfile.packages["node_modules/fixture-consumer-b"]?.integrity,
      );

      const deploymentShared = await readJson<PackageJson>(
        path.join(deploymentDir, "node_modules/fixture-shared/package.json"),
      );
      const nestedShared = await readJson<PackageJson>(
        path.join(
          deploymentDir,
          "node_modules/fixture-consumer-b/node_modules/fixture-shared/package.json",
        ),
      );
      const localLib = await readJson<PackageJson>(
        path.join(deploymentDir, "node_modules/fixture-local-lib/package.json"),
      );
      const devLocal = await readJson<PackageJson>(
        path.join(deploymentDir, "node_modules/fixture-dev-local/package.json"),
      );
      const devRegistryPackage = await readJson<PackageJson>(
        path.join(deploymentDir, "node_modules/fixture-dev-registry/package.json"),
      );

      assert.equal(deploymentShared.version, "1.0.0");
      assert.equal(nestedShared.version, "2.0.0");
      assert.equal(localLib.version, "1.0.0");
      assert.equal(devLocal.version, "2.0.0");
      assert.equal(devRegistryPackage.version, "4.0.0");
      await assertMissing(path.join(deploymentDir, "node_modules/fixture-unrelated-workspace"));
      await assertMissing(path.join(deploymentDir, "node_modules/fixture-unrelated-registry"));
    } finally {
      await closeServer(server);
      await fs.rm(repositoryDir, { recursive: true, force: true });
    }
  });

  it("runs npm ci when a retained registry package requires a peer dependency", async () => {
    const repositoryDir = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-npm-ci-peer-"));
    const tarballs = new Map<string, string>();
    const { server, origin } = await startTarballServer(tarballs);

    try {
      const peer = await packPackage(repositoryDir, tarballs, {
        name: "fixture-peer",
        version: "1.0.0",
      });
      const consumer = await packPackage(repositoryDir, tarballs, {
        name: "fixture-peer-consumer",
        version: "1.0.0",
        peerDependencies: { "fixture-peer": "^1.0.0" },
      });

      await writeJson(path.join(repositoryDir, "package.json"), {
        name: "fixture-repository",
        private: true,
        workspaces: ["packages/*"],
        devDependencies: { "fixture-peer": `${origin}/${peer}` },
      });
      await writeJson(path.join(repositoryDir, "packages/app/package.json"), {
        name: "fixture-app",
        version: "1.0.0",
        dependencies: { "fixture-peer-consumer": `${origin}/${consumer}` },
      });
      await fs.writeFile(
        path.join(repositoryDir, "packages/app/index.js"),
        "export const app = 1;\n",
        "utf8",
      );

      await execa(
        "npm",
        ["install", "--package-lock-only", "--ignore-scripts", "--no-audit", "--no-fund"],
        { cwd: repositoryDir },
      );
      const sourceLockfile = await readJson<NpmLockfile>(
        path.join(repositoryDir, "package-lock.json"),
      );
      const deploymentDir = path.join(repositoryDir, "deployment");

      await execa(
        "node",
        [
          "--import",
          "tsx",
          CLI_PATH,
          "--target",
          "fixture-app",
          "--repository-dir",
          repositoryDir,
          "--deployment-dir",
          deploymentDir,
          "--install",
          "npm-ci",
        ],
        { cwd: PROJECT_DIR },
      );
      const projectedLockfile = await readJson<NpmLockfile>(
        path.join(deploymentDir, "package-lock.json"),
      );
      const installedPeer = await readJson<PackageJson>(
        path.join(deploymentDir, "node_modules/fixture-peer/package.json"),
      );

      assert.equal(installedPeer.version, "1.0.0");
      assert.equal(
        projectedLockfile.packages["node_modules/fixture-peer"]?.integrity,
        sourceLockfile.packages["node_modules/fixture-peer"]?.integrity,
      );
    } finally {
      await closeServer(server);
      await fs.rm(repositoryDir, { recursive: true, force: true });
    }
  });
  it("uses the npm configuration supplied by --npmrc", async () => {
    const temporaryDir = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-npmrc-"));

    try {
      const repositoryDir = path.join(temporaryDir, "repo");
      await writeJson(path.join(repositoryDir, "package.json"), {
        name: "fixture-repository",
        private: true,
        workspaces: ["packages/*"],
      });
      await writeJson(path.join(repositoryDir, "packages/app/package.json"), {
        name: "fixture-app",
        version: "1.0.0",
        dependencies: { "fixture-local": "workspace:*" },
      });
      await writeJson(path.join(repositoryDir, "packages/local/package.json"), {
        name: "fixture-local",
        version: "1.0.0",
      });
      await writeJson(path.join(repositoryDir, "package-lock.json"), {
        name: "fixture-repository",
        lockfileVersion: 3,
        requires: true,
        packages: {
          "": {
            name: "fixture-repository",
            workspaces: ["packages/*"],
          },
          "packages/app": {
            name: "fixture-app",
            version: "1.0.0",
            dependencies: { "fixture-local": "workspace:*" },
          },
          "packages/local": {
            name: "fixture-local",
            version: "1.0.0",
          },
          "node_modules/fixture-app": {
            resolved: "packages/app",
            link: true,
          },
          "node_modules/fixture-local": {
            resolved: "packages/local",
            link: true,
          },
        },
      });

      const baseArgs = [
        "--import",
        "tsx",
        CLI_PATH,
        "--target",
        "fixture-app",
        "--repository-dir",
        repositoryDir,
      ];
      const defaultDeploymentDir = path.join(temporaryDir, "default-deployment");
      await execa("node", [...baseArgs, "--deployment-dir", defaultDeploymentDir], {
        cwd: PROJECT_DIR,
      });
      await fs.access(path.join(defaultDeploymentDir, "node_modules/fixture-local/package.json"));

      const npmrc = path.join(temporaryDir, "install.npmrc");
      await fs.writeFile(npmrc, "dry-run=true\n", "utf8");
      const configuredDeploymentDir = path.join(temporaryDir, "configured-deployment");
      const configured = await execa(
        "node",
        [
          ...baseArgs,
          "--deployment-dir",
          configuredDeploymentDir,
          "--npmrc",
          path.relative(PROJECT_DIR, npmrc),
        ],
        { cwd: PROJECT_DIR, reject: false },
      );

      assert.equal(configured.exitCode, 1);
      assert.match(configured.stderr, /Local dependency "fixture-local" is not present/);
      await assertMissing(
        path.join(configuredDeploymentDir, "node_modules/fixture-local/package.json"),
      );
    } finally {
      await fs.rm(temporaryDir, { recursive: true, force: true });
    }
  });
});
