// Generated by AI (UnitTest MCP)
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import { createServer, type Server } from "node:http";
import * as os from "node:os";
import * as path from "node:path";
import { describe, it } from "node:test";

import { execa } from "execa";

import { runWsDeploy } from "../src/deploy.js";
import type { NpmLockfile, PackageJson } from "../src/types.js";

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, undefined, 2)}\n`, "utf8");
}

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await fs.readFile(file, "utf8")) as T;
}

async function startTarballServer(files: Map<string, string>): Promise<{
  server: Server;
  origin: string;
}> {
  const server = createServer(async (request, response) => {
    const pathname = decodeURIComponent(new URL(request.url ?? "/", "http://localhost").pathname);
    const file = files.get(pathname);
    if (!file) {
      response.writeHead(404).end();
      return;
    }
    try {
      response.writeHead(200, { "content-type": "application/octet-stream" });
      response.end(await fs.readFile(file));
    } catch {
      response.writeHead(500).end();
    }
  });
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", resolve);
  });
  const address = server.address();
  assert.ok(address && typeof address === "object");
  return { server, origin: `http://127.0.0.1:${address.port}` };
}

async function closeServer(server: Server): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    server.close((error) => {
      if (error) {
        reject(error);
        return;
      }
      resolve();
    });
  });
}

async function packPackage(
  root: string,
  tarballs: Map<string, string>,
  manifest: PackageJson,
): Promise<string> {
  const safeName = manifest.name?.replace(/[^a-zA-Z0-9.-]/g, "-") ?? "package";
  const sourceDir = path.join(root, "package-sources", `${safeName}-${manifest.version}`);
  const outputDir = path.join(root, "tarballs");
  await writeJson(path.join(sourceDir, "package.json"), manifest);
  await fs.writeFile(
    path.join(sourceDir, "index.js"),
    `export const version = ${JSON.stringify(manifest.version)};\n`,
    "utf8",
  );
  await fs.mkdir(outputDir, { recursive: true });
  const result = await execa("npm", ["pack", "--json", "--pack-destination", outputDir], {
    cwd: sourceDir,
  });
  const [{ filename }] = JSON.parse(result.stdout) as [{ filename: string }];
  tarballs.set(`/${filename}`, path.join(outputDir, filename));
  return filename;
}

async function assertMissing(file: string): Promise<void> {
  await assert.rejects(fs.access(file));
}

describe("npm ci deployment E2E", () => {
  it("installs the projected closure with exact nested versions and excludes unrelated packages", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "ws-deploy-npm-ci-"));
    const tarballs = new Map<string, string>();
    const { server, origin } = await startTarballServer(tarballs);

    try {
      const sharedV1 = await packPackage(root, tarballs, {
        name: "fixture-shared",
        version: "1.0.0",
      });
      const sharedV2 = await packPackage(root, tarballs, {
        name: "fixture-shared",
        version: "2.0.0",
      });
      const consumerA = await packPackage(root, tarballs, {
        name: "fixture-consumer-a",
        version: "1.0.0",
        dependencies: { "fixture-shared": `${origin}/${sharedV1}` },
      });
      const consumerB = await packPackage(root, tarballs, {
        name: "fixture-consumer-b",
        version: "1.0.0",
        dependencies: { "fixture-shared": `${origin}/${sharedV2}` },
      });
      const unrelated = await packPackage(root, tarballs, {
        name: "fixture-unrelated-registry",
        version: "9.0.0",
      });
      const devRegistry = await packPackage(root, tarballs, {
        name: "fixture-dev-registry",
        version: "4.0.0",
      });

      await writeJson(path.join(root, "package.json"), {
        name: "fixture-root",
        private: true,
        workspaces: ["packages/*"],
      });
      await writeJson(path.join(root, "packages/app/package.json"), {
        name: "fixture-app",
        version: "1.0.0",
        dependencies: {
          "fixture-consumer-a": `${origin}/${consumerA}`,
          "fixture-consumer-b": `${origin}/${consumerB}`,
          "fixture-local-lib": "^1.0.0",
        },
        devDependencies: {
          "fixture-dev-local": "^2.0.0",
          "fixture-dev-registry": `${origin}/${devRegistry}`,
        },
      });
      await fs.writeFile(
        path.join(root, "packages/app/index.js"),
        "export const app = 1;\n",
        "utf8",
      );
      await writeJson(path.join(root, "packages/local-lib/package.json"), {
        name: "fixture-local-lib",
        version: "1.0.0",
      });
      await fs.writeFile(
        path.join(root, "packages/local-lib/index.js"),
        "export const local = 1;\n",
        "utf8",
      );
      await writeJson(path.join(root, "packages/dev-local/package.json"), {
        name: "fixture-dev-local",
        version: "2.0.0",
      });
      await fs.writeFile(
        path.join(root, "packages/dev-local/index.js"),
        "export const dev = 1;\n",
        "utf8",
      );
      await writeJson(path.join(root, "packages/unrelated/package.json"), {
        name: "fixture-unrelated-workspace",
        version: "1.0.0",
        dependencies: { "fixture-unrelated-registry": `${origin}/${unrelated}` },
      });

      await execa(
        "npm",
        ["install", "--package-lock-only", "--ignore-scripts", "--no-audit", "--no-fund"],
        { cwd: root },
      );
      const sourceLockfile = await readJson<NpmLockfile>(path.join(root, "package-lock.json"));
      const deployDir = path.join(root, "deployment");

      const result = await runWsDeploy({
        repoRoot: root,
        targetWorkspace: "fixture-app",
        deployDir,
        installMode: "npm-ci",
        includeDevDependencies: true,
      });

      assert.equal(result.warnings.length, 0);
      assert.equal(
        result.lockfile.packages["node_modules/fixture-consumer-a"]?.integrity,
        sourceLockfile.packages["node_modules/fixture-consumer-a"]?.integrity,
      );
      assert.equal(
        result.lockfile.packages["node_modules/fixture-consumer-b"]?.integrity,
        sourceLockfile.packages["node_modules/fixture-consumer-b"]?.integrity,
      );

      const rootShared = await readJson<PackageJson>(
        path.join(deployDir, "node_modules/fixture-shared/package.json"),
      );
      const nestedShared = await readJson<PackageJson>(
        path.join(
          deployDir,
          "node_modules/fixture-consumer-b/node_modules/fixture-shared/package.json",
        ),
      );
      const localLib = await readJson<PackageJson>(
        path.join(deployDir, "node_modules/fixture-local-lib/package.json"),
      );
      const devLocal = await readJson<PackageJson>(
        path.join(deployDir, "node_modules/fixture-dev-local/package.json"),
      );
      const devRegistryPackage = await readJson<PackageJson>(
        path.join(deployDir, "node_modules/fixture-dev-registry/package.json"),
      );

      assert.equal(rootShared.version, "1.0.0");
      assert.equal(nestedShared.version, "2.0.0");
      assert.equal(localLib.version, "1.0.0");
      assert.equal(devLocal.version, "2.0.0");
      assert.equal(devRegistryPackage.version, "4.0.0");
      await assertMissing(path.join(deployDir, "node_modules/fixture-unrelated-workspace"));
      await assertMissing(path.join(deployDir, "node_modules/fixture-unrelated-registry"));
    } finally {
      await closeServer(server);
      await fs.rm(root, { recursive: true, force: true });
    }
  });
});
